name: Validate Renovate Config

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'renovate.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.2

      - name: Validate Renovate Config
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3
